In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import pickle as pkl
import math
import requests
import csv
import sklearn
import json
import requests
from sklearn import preprocessing

In [2]:
def time_convert(time) :
      
    time = int(time)

    r1 = time %100

    if(r1<30) :
    
        time = time - r1
    
    elif(r1>=30) :
    
        time = time + (100 - r1)
    
    if(time == 2400):
    
        time = 0
    
    return time

In [3]:
flight_data = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\Flight_Data.csv')

In [4]:
flight_data.isnull().sum()

Year                   0
Quarter                0
Month                  0
DayofMonth             0
FlightDate             0
OriginAirportID        0
Origin                 0
DestAirportID          0
CRSDepTime             0
DepTime            20972
DepDelayMinutes    20979
DepDel15           20979
CRSArrTime             0
ArrTime            22072
ArrDelayMinutes    25852
ArrDel15           25852
dtype: int64

In [5]:
flight_data = flight_data[flight_data['ArrDelayMinutes'].notna()]

In [6]:
flight_data.isnull().sum()

Year               0
Quarter            0
Month              0
DayofMonth         0
FlightDate         0
OriginAirportID    0
Origin             0
DestAirportID      0
CRSDepTime         0
DepTime            0
DepDelayMinutes    0
DepDel15           0
CRSArrTime         0
ArrTime            0
ArrDelayMinutes    0
ArrDel15           0
dtype: int64

In [7]:
time_change = []

for i in flight_data['CRSDepTime'] :
    
    newtime = time_convert(i)
    
    time_change.append(newtime)

flight_data['DepartureTime'] = time_change

In [8]:
weather_data = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\weather\Weather_Data.csv')

In [10]:
final_dataframe = pd.merge(flight_data,weather_data,how = 'inner',left_on = ['Origin','DepartureTime','FlightDate'],right_on = ['Airport','time','Date'])

final_dataframe = final_dataframe.drop(['Origin','DepartureTime'],axis = 1)

In [11]:
final_dataframe

,Year,Quarter,Month,DayofMonth,FlightDate,OriginAirportID,DestAirportID,CRSDepTime,DepTime,DepDelayMinutes,...,WindGustKmph,visibility,weatherCode,tempF,WindChillF,winddirDegree,humidity,time,Airport,Date
0,2016,1,1,1,2016-01-01,14747,12478,745,741.0,0.0,...,8,10,113,34,29,108,65,800,SEA,2016-01-01
1,2016,1,1,1,2016-01-01,14747,14107,820,821.0,1.0,...,8,10,113,34,29,108,65,800,SEA,2016-01-01
2,2016,1,1,1,2016-01-01,14747,11292,759,754.0,0.0,...,8,10,113,34,29,108,65,800,SEA,2016-01-01
3,2016,1,1,1,2016-01-01,14747,12266,738,740.0,2.0,...,8,10,113,34,29,108,65,800,SEA,2016-01-01
4,2016,1,1,1,2016-01-01,14747,10397,745,742.0,0.0,...,8,10,113,34,29,108,65,800,SEA,2016-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1851428,2017,4,12,17,2017-12-17,12266,11618,1424,1541.0,77.0,...,7,10,119,59,59,91,74,1400,IAH,2017-12-17
1851429,2017,4,12,17,2017-12-17,12266,11618,1300,1257.0,0.0,...,8,10,122,57,57,77,77,1300,IAH,2017-12-17
1851430,2017,4,12,17,2017-12-17,12266,11292,1304,1259.0,0.0,...,8,10,122,57,57,77,77,1300,IAH,2017-12-17
1851431,2017,4,12,17,2017-12-17,11618,13303,2100,2057.0,0.0,...,16,10,122,32,29,123,88,2100,EWR,2017-12-17
1851432,2017,4,12,17,2017-12-17,13930,14771,2322,2312.0,0.0,...,12,6,122,37,34,219,90,2300,ORD,2017-12-17

In [12]:
final_dataframe.to_csv(r'C:\Users\badri\Desktop\ML-Project\Flight_Weather.csv',index = False)