In [3]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import pickle as pkl
import math
import requests
import csv
import sklearn

In [2]:
airports = ['ATL','CLT','DEN','DFW','EWR','IAH','JFK','LAS','LAX','MCO','MIA','ORD','PHX','SEA','SFO']

In [3]:
data_2016_1 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_1\On_Time_On_Time_Performance_2016_1.csv')

data_2016_2 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_2\On_Time_On_Time_Performance_2016_2.csv')

data_2016_3 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_3\On_Time_On_Time_Performance_2016_3.csv')

data_2016_4 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_4\On_Time_On_Time_Performance_2016_4.csv')

data_2016_5 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_5\On_Time_On_Time_Performance_2016_5.csv')

data_2016_6 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_6\On_Time_On_Time_Performance_2016_6.csv')

data_2016_7 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_7\On_Time_On_Time_Performance_2016_7.csv')

data_2016_8 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_8\On_Time_On_Time_Performance_2016_8.csv')

data_2016_9 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_9\On_Time_On_Time_Performance_2016_9.csv')

data_2016_10 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_10\On_Time_On_Time_Performance_2016_10.csv')

data_2016_11 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_11\On_Time_On_Time_Performance_2016_11.csv')

data_2016_12 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\On_Time_On_Time_Performance_2016_12\On_Time_On_Time_Performance_2016_12.csv')

C:\Users\badri\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (77) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\badri\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (77,84) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\badri\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (48,77,84) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\badri\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (48,77,84,85) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\badri\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (48,69,76,77,84) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
data_2016_1_origin = data_2016_1[data_2016_1['Origin'].isin(airports)]

data_2016_1_a = data_2016_1_origin[data_2016_1_origin['Dest'].isin(airports)]

data_2016_2_origin = data_2016_2[data_2016_2['Origin'].isin(airports)]

data_2016_2_a = data_2016_2_origin[data_2016_2_origin['Dest'].isin(airports)]

data_2016_3_origin = data_2016_3[data_2016_3['Origin'].isin(airports)]

data_2016_3_a = data_2016_3_origin[data_2016_3_origin['Dest'].isin(airports)]

data_2016_4_origin = data_2016_4[data_2016_4['Origin'].isin(airports)]

data_2016_4_a = data_2016_4_origin[data_2016_4_origin['Dest'].isin(airports)]

data_2016_5_origin = data_2016_5[data_2016_5['Origin'].isin(airports)]

data_2016_5_a = data_2016_5_origin[data_2016_5_origin['Dest'].isin(airports)]

data_2016_6_origin = data_2016_6[data_2016_6['Origin'].isin(airports)]

data_2016_6_a = data_2016_6_origin[data_2016_6_origin['Dest'].isin(airports)]

data_2016_7_origin = data_2016_7[data_2016_7['Origin'].isin(airports)]

data_2016_7_a = data_2016_7_origin[data_2016_7_origin['Dest'].isin(airports)]

data_2016_8_origin = data_2016_8[data_2016_8['Origin'].isin(airports)]

data_2016_8_a = data_2016_8_origin[data_2016_8_origin['Dest'].isin(airports)]

data_2016_9_origin = data_2016_9[data_2016_9['Origin'].isin(airports)]

data_2016_9_a = data_2016_9_origin[data_2016_9_origin['Dest'].isin(airports)]

data_2016_10_origin = data_2016_10[data_2016_10['Origin'].isin(airports)]

data_2016_10_a = data_2016_10_origin[data_2016_10_origin['Dest'].isin(airports)]

data_2016_11_origin = data_2016_11[data_2016_11['Origin'].isin(airports)]

data_2016_11_a = data_2016_11_origin[data_2016_11_origin['Dest'].isin(airports)]

data_2016_12_origin = data_2016_12[data_2016_12['Origin'].isin(airports)]

data_2016_12_a = data_2016_12_origin[data_2016_12_origin['Dest'].isin(airports)]

data_2016_A = data_2016_1_a.append(data_2016_2_a,ignore_index = True).append(data_2016_3_a,ignore_index = True).append(data_2016_4_a,ignore_index = True)

data_2016_B = data_2016_5_a.append(data_2016_6_a,ignore_index = True).append(data_2016_7_a,ignore_index = True).append(data_2016_8_a,ignore_index = True)

data_2016_C = data_2016_9_a.append(data_2016_10_a,ignore_index = True).append(data_2016_11_a,ignore_index = True).append(data_2016_12_a,ignore_index = True)

data_2016 = data_2016_A.append(data_2016_B,ignore_index = True).append(data_2016_C,ignore_index = True)

In [5]:
data_2016.to_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2016\Flight_Data_2016.csv',index = False)

In [7]:
data_2017_1 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_1\On_Time_On_Time_Performance_2017_1.csv')

data_2017_2 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_2\On_Time_On_Time_Performance_2017_2.csv')

data_2017_3 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_3\On_Time_On_Time_Performance_2017_3.csv')

data_2017_4 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_4\On_Time_On_Time_Performance_2017_4.csv')

data_2017_5 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_5\On_Time_On_Time_Performance_2017_5.csv')

data_2017_6 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_6\On_Time_On_Time_Performance_2017_6.csv')

data_2017_7 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_7\On_Time_On_Time_Performance_2017_7.csv')

data_2017_8 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_8\On_Time_On_Time_Performance_2017_8.csv')

data_2017_9 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_9\On_Time_On_Time_Performance_2017_9.csv')

data_2017_10 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_10\On_Time_On_Time_Performance_2017_10.csv')

data_2017_11 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_11\On_Time_On_Time_Performance_2017_11.csv')

data_2017_12 = pd.read_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\On_Time_On_Time_Performance_2017_12\On_Time_On_Time_Performance_2017_12.csv')

C:\Users\badri\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (48,77) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
data_2017_1_origin = data_2017_1[data_2017_1['Origin'].isin(airports)]

data_2017_1_a = data_2017_1_origin[data_2017_1_origin['Dest'].isin(airports)]

data_2017_2_origin = data_2017_2[data_2017_2['Origin'].isin(airports)]

data_2017_2_a = data_2017_2_origin[data_2017_2_origin['Dest'].isin(airports)]

data_2017_3_origin = data_2017_3[data_2017_3['Origin'].isin(airports)]

data_2017_3_a = data_2017_3_origin[data_2017_3_origin['Dest'].isin(airports)]

data_2017_4_origin = data_2017_4[data_2017_4['Origin'].isin(airports)]

data_2017_4_a = data_2017_4_origin[data_2017_4_origin['Dest'].isin(airports)]

data_2017_5_origin = data_2017_5[data_2017_5['Origin'].isin(airports)]

data_2017_5_a = data_2017_5_origin[data_2017_5_origin['Dest'].isin(airports)]

data_2017_6_origin = data_2017_6[data_2017_6['Origin'].isin(airports)]

data_2017_6_a = data_2017_6_origin[data_2017_6_origin['Dest'].isin(airports)]

data_2017_7_origin = data_2017_7[data_2017_7['Origin'].isin(airports)]

data_2017_7_a = data_2017_7_origin[data_2017_7_origin['Dest'].isin(airports)]

data_2017_8_origin = data_2017_8[data_2017_8['Origin'].isin(airports)]

data_2017_8_a = data_2017_8_origin[data_2017_8_origin['Dest'].isin(airports)]

data_2017_9_origin = data_2017_9[data_2017_9['Origin'].isin(airports)]

data_2017_9_a = data_2017_9_origin[data_2017_9_origin['Dest'].isin(airports)]

data_2017_10_origin = data_2017_10[data_2017_10['Origin'].isin(airports)]

data_2017_10_a = data_2017_10_origin[data_2017_10_origin['Dest'].isin(airports)]

data_2017_11_origin = data_2017_11[data_2017_11['Origin'].isin(airports)]

data_2017_11_a = data_2017_11_origin[data_2017_11_origin['Dest'].isin(airports)]

data_2017_12_origin = data_2017_12[data_2017_12['Origin'].isin(airports)]

data_2017_12_a = data_2017_12_origin[data_2017_12_origin['Dest'].isin(airports)]

data_2017_A = data_2017_1_a.append(data_2017_2_a,ignore_index = True).append(data_2017_3_a,ignore_index = True).append(data_2017_4_a,ignore_index = True)

data_2017_B = data_2017_5_a.append(data_2017_6_a,ignore_index = True).append(data_2017_7_a,ignore_index = True).append(data_2017_8_a,ignore_index = True)

data_2017_C = data_2017_9_a.append(data_2017_10_a,ignore_index = True).append(data_2017_11_a,ignore_index = True).append(data_2017_12_a,ignore_index = True)

data_2017 = data_2017_A.append(data_2017_B,ignore_index = True).append(data_2017_C,ignore_index = True)

In [10]:
data_2017.to_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\2017\Flight_Data_2017.csv',index = False)

flight_data = data_2016.append(data_2017,ignore_index = True)

In [11]:
wanted_columns = ['FlightDate','Quarter','Year','Month','DayofMonth' ,'DepTime','DepDel15','CRSDepTime','DepDelayMinutes','OriginAirportID','DestAirportID','ArrTime','CRSArrTime','ArrDel15','ArrDelayMinutes','Origin']

unwanted_columns = []

for i in flight_data.columns : 
    
    if i not in wanted_columns:
        
        unwanted_columns.append(i)

In [12]:
flight_data = flight_data.drop(unwanted_columns,axis = 1).drop_duplicates()

In [13]:
flight_data

,Year,Quarter,Month,DayofMonth,FlightDate,OriginAirportID,Origin,DestAirportID,CRSDepTime,DepTime,DepDelayMinutes,DepDel15,CRSArrTime,ArrTime,ArrDelayMinutes,ArrDel15
0,2016,1,1,1,2016-01-01,14747,SEA,12478,745,741.0,0.0,0.0,1602,1610.0,8.0,0.0
1,2016,1,1,2,2016-01-02,14747,SEA,12478,745,737.0,0.0,0.0,1602,1613.0,11.0,0.0
2,2016,1,1,3,2016-01-03,14747,SEA,12478,745,743.0,0.0,0.0,1602,1547.0,0.0,0.0
3,2016,1,1,4,2016-01-04,14747,SEA,12478,745,737.0,0.0,0.0,1602,1551.0,0.0,0.0
4,2016,1,1,5,2016-01-05,14747,SEA,12478,710,708.0,0.0,0.0,1527,1524.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877291,2017,4,12,17,2017-12-17,13930,ORD,12266,1030,1024.0,0.0,0.0,1326,1314.0,0.0,0.0
1877292,2017,4,12,17,2017-12-17,12892,LAX,11618,1156,1148.0,0.0,0.0,2017,1939.0,0.0,0.0
1877293,2017,4,12,17,2017-12-17,12266,IAH,11292,737,739.0,2.0,0.0,909,904.0,0.0,0.0
1877294,2017,4,12,17,2017-12-17,11298,DFW,11292,1638,1632.0,0.0,0.0,1747,1727.0,0.0,0.0
1877295,2017,4,12,17,2017-12-17,13204,MCO,11618,1008,1007.0,0.0,0.0,1245,1222.0,0.0,0.0

In [14]:
flight_data.to_csv(r'C:\Users\badri\Desktop\ML-Project\Flight Data\Flight_Data.csv',index = False)